### ISSUE TITLE
Implement Immunization component

### ISSUE THREAD

**Issue by sidharthramesh** [sidharthramesh/healthgate#1]
Front end component for generation Immunisation FHIR Resource: http://hl7.org/fhir/immunization.html

**Comment by sidharthramesh** [comment]
Maybe use components from Vue + Bulma like this? : https://buefy.org/documentation/collapse

**Comment by tashes** [comment]
![j](https://user-images.githubusercontent.com/4820063/75948361-49558400-5ec9-11ea-8579-429015024c52.jpeg)
![j1](https://user-images.githubusercontent.com/4820063/75948364-4b1f4780-5ec9-11ea-9970-3453aace638c.jpeg)
![j2](https://user-images.githubusercontent.com/4820063/75948365-4bb7de00-5ec9-11ea-86e4-584860f1d75e.jpeg)

**Comment by sidharthramesh** [comment]
Need to do something about vitamin A. It's technically not an "Immunization", but is given along with it. Need to look for another FHIR resource.

**Comment by sidharthramesh** [comment]
Also would like someone from Paediatrics to review the immunization schedule with all the details like dosage, site, route and especially the exact vaccination code (Monovalent, pentavalent etc) in `immunization/default.js`. Help with displaying the json as a nice table would be appreciated. 

Reference vaccination codes found [here](http://hl7.org/fhir/valueset-vaccine-code.html)

**Comment by sidharthramesh** [comment]
Fixed in #8
